// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD-2gye24tQCOFUGO8VvH7FPIuaH5K_fU',
    appId: '1:441881654485:web:520b306f8bc06d92461e5c',
    messagingSenderId: '441881654485',
    projectId: 'decisionapp-82ef0',
    authDomain: 'decisionapp-82ef0.firebaseapp.com',
    storageBucket: 'decisionapp-82ef0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeUrsmcM7a5fEUpYrQvjFLLbo9oBJSDDY',
    appId: '1:441881654485:android:d9e4258539d002c1461e5c',
    messagingSenderId: '441881654485',
    projectId: 'decisionapp-82ef0',
    storageBucket: 'decisionapp-82ef0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaQlssV1gMrTAPv4l1-nk3W1iSpebXZDw',
    appId: '1:441881654485:ios:e08ba1712e0fbd18461e5c',
    messagingSenderId: '441881654485',
    projectId: 'decisionapp-82ef0',
    storageBucket: 'decisionapp-82ef0.appspot.com',
    iosClientId: '441881654485-poap1680m6cn4lfavogc4q20gcmq2b1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.decisionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaQlssV1gMrTAPv4l1-nk3W1iSpebXZDw',
    appId: '1:441881654485:ios:deef059a7bdcd0d2461e5c',
    messagingSenderId: '441881654485',
    projectId: 'decisionapp-82ef0',
    storageBucket: 'decisionapp-82ef0.appspot.com',
    iosClientId: '441881654485-vkb01daph8q1eq925445rohdjc2grk37.apps.googleusercontent.com',
    iosBundleId: 'com.example.decisionapp.RunnerTests',
  );
}
